version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /
    pattern: "**"
    owner: root
hooks:
  AfterInstall:
    - location: deploy/deps_install
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: deploy/app_start
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy/server_restart
      timeout: 60
      runas: root