version: 0.0
os: linux
files:
    - source: /
      destination: /app/jordan-tart
hooks:
#  ApplicationStop:
#    - location: deploy/index.js
#      timeout: 180
  BeforeInstall:
    - location: deploy/index.js
      timeout: 180
  AfterInstall:
    - location: deploy/index.js
      timeout: 180
  ApplicationStart:
    - location: deploy/index.js
      timeout: 180
  ValidateService:
    - location: deploy/index.js
      timeout: 180