version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/jordan-tart
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: deploy/app_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: deploy/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: deploy/app_start.sh
      timeout: 120
      runas: ubuntu