version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy/deps_install
      timeout: 1200
      runas: ubuntu
  ApplicationStart:
    - location: deploy/app_start
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: deploy/server_restart
      timeout: 60
      runas: ubuntu